name: Docker Image CI

on:
    push:
        branches:
            - "deploy"
            # - "test-deploy"
            # tags:
            #   - "v*"
            #   - "t*"

jobs:
    build:
        # if: ${{ startsWith(github.ref, 'refs/tags/t') || startsWith(github.ref, 'refs/heads/test-deploy/') || startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/deploy/') }}
        runs-on: ubuntu-latest

        steps:
            # 拉取main分支代码
            - name: Checkout
              uses: actions/checkout@v2
              uses: actions/setup-node@v2
              with:
                node-version: 16.13

            # 制作docker镜像并推送到阿里云容器镜像服务
            - name: build and push docker image
              run: yarn install
              run: yarn build

            - name: Upload dist ssh
              uses: easingthemes/ssh-deploy@v2.1.6
              with:
                REMOTE_USER: 'root'
                REMOTE_HOST: '${{ secrets.ONLINE_HOST }}' #测试服务器地址
                SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIV_KEY }}
                TARGET: '/root/yakit-online/' #服务器中，代码部署的位置
